### PR TITLE
External ffmpeg support

### PR DESCRIPTION
**Pull request by jianjunz**
This change makes it easier for developers to use a specific version of FFmpeg.

### CODE REVIEW

**Review by dvrogozh — CHANGES_REQUESTED** [review]
This does not work for me. Build (for x64) fails with:
```
$ python3 .\\scripts\\build-win.py --gn_gen --sdk --cloud_gaming --output_path dist-x64 --scheme release --arch x64
<...>
FAILED: obj/third_party/ffmpeg/ffmpeg_internal/mpegaudiodec_fixed.obj 
../../third_party/ffmpeg/libavcodec/mpegaudiodec_fixed.c(22): fatal error C1083: Cannot open include file: 'config_components.h': No such file or directory
<...>
```

So, internal ffmpeg sources were not actually excluded from the build. Also, if idea is to switch to external ffmpeg source, then why do we need internal ffmpeg source copy? can it be completely dropped on gclient sync level?

**Comment by jianjunz** [comment]
This PR depends on https://github.com/open-webrtc-toolkit/owt-deps-webrtc/pull/191, which removes ffmpeg from libwebrtc. These two need to be merged at the same time.

**Comment by jianjunz** [comment]
This change has been updated to include https://github.com/open-webrtc-toolkit/owt-deps-webrtc/pull/191.
